import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  getAll,
  insert,
  query,
  queryFirst,
  update,
  wrapSuccess,
  wrapFail,
} from "./database";
import { daysUntil, todayLocal } from "../utils/reminder";
import { STORAGE_KEYS, REMIND_DEFAULTS } from "../utils/constant";

function pad(n) { return String(n).padStart(2, "0"); }

function formatLocalDate(date) {
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

const TABLE = "reminders";

// 计算重要日子下一次发生日期
function computeNextOccurrence(dateStr, type) {
  if (!dateStr) return null;
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const [y, m, d] = dateStr.split("-").map(Number);
  const target = new Date(y, m - 1, d);

  if (type === "once") {
    return { date: target, daysUntil: Math.ceil((target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)) };
  }

  let next = new Date(today.getFullYear(), m - 1, d);
  if (next.getTime() < today.getTime()) {
    next = new Date(today.getFullYear() + 1, m - 1, d);
  }
  const diff = Math.ceil((next.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  return { date: next, daysUntil: diff };
}

// 防止并发自动生成提醒导致重复记录
let _genPromise = null;
async function ensureRemindersGenerated() {
  if (_genPromise) return _genPromise;
  _genPromise = (async () => {
    const config = await getRemindConfig();
    await autoGenerateScheduleReminders(config.scheduleDays);
    await autoGenerateDurableExpiryReminders(config.durableDays);
    await autoGenerateImportantDateReminders(config.importantDateDays);
  })();
  try {
    await _genPromise;
  } finally {
    _genPromise = null;
  }
}

const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 };

/** 计算计划动态描述 */
function scheduleDesc(item) {
  const today = todayLocal();
  const days = item.end_date ? daysUntil(item.end_date) : 999;

  if (days < 0) return { desc: "common.incomplete", daysLeft: "common.incomplete", daysLeftNum: days };

  if (item.start_date && item.start_date > today) {
    const startDays = daysUntil(item.start_date);
    if (startDays > 0) return { desc: "common.startsIn", descCount: startDays, daysLeft: String(startDays), daysLeftNum: startDays };
    return { desc: "common.startsToday", daysLeft: "common.today", daysLeftNum: 0 };
  }

  if (days === 0) return { desc: "common.endsToday", daysLeft: "common.today", daysLeftNum: 0 };
  return { desc: "common.daysLeft", descCount: days, daysLeft: String(days), daysLeftNum: days };
}

/** 计算物品动态描述 */
function durableDesc(item) {
  const days = item.expiry_date ? daysUntil(item.expiry_date) : 999;

  if (days < 0) return { desc: "common.expired", daysLeft: "common.expired", daysLeftNum: days };
  if (days === 0) return { desc: "common.expired", daysLeft: "common.expired", daysLeftNum: 0 };
  return { desc: "common.expiresIn", descCount: days, daysLeft: String(days), daysLeftNum: days };
}

/** 读取提醒天数配置（带默认值） */
async function getRemindConfig() {
  try {
    const [s, d, id] = await Promise.all([
      AsyncStorage.getItem(STORAGE_KEYS.scheduleRemindDays),
      AsyncStorage.getItem(STORAGE_KEYS.durableRemindDays),
      AsyncStorage.getItem(STORAGE_KEYS.importantDateRemindDays),
    ]);
    return {
      scheduleDays: s !== null ? Number(s) : REMIND_DEFAULTS.scheduleRemindDays,
      durableDays: d !== null ? Number(d) : REMIND_DEFAULTS.durableRemindDays,
      importantDateDays: id !== null ? Number(id) : REMIND_DEFAULTS.importantDateRemindDays,
    };
  } catch {
    return {
      scheduleDays: REMIND_DEFAULTS.scheduleRemindDays,
      durableDays: REMIND_DEFAULTS.durableRemindDays,
      importantDateDays: REMIND_DEFAULTS.importantDateRemindDays,
    };
  }
}

async function autoGenerateScheduleReminders(scheduleDays) {
  const today = todayLocal();

  // 查询开启提醒且状态为未开始/未完成的计划
  const schedules = await query(
    "SELECT * FROM schedules WHERE reminder_enabled = 1 AND status != 'done' AND status != 'in_progress'"
  );

  // 建立有效计划集合，用于清理旧提醒
  const validSet = new Set(schedules.map((s) => s.id));

  // 清理不再符合条件的旧提醒 + 去除重复记录
  const activeScheduleReminders = await query(
    "SELECT * FROM reminders WHERE module_type = 'schedule' AND is_active = 1 AND dismissed = 0"
  );
  const scheduleReminderMap = new Map();
  for (const r of activeScheduleReminders) {
    if (!validSet.has(r.module_id)) {
      await update(TABLE, r.id, { is_active: 0 });
      continue;
    }
    // 同一 module_id 有多条记录时，保留最新的，停用其余的
    const existing = scheduleReminderMap.get(r.module_id);
    if (existing) {
      await update(TABLE, r.id, { is_active: 0 });
    } else {
      scheduleReminderMap.set(r.module_id, r);
    }
  }

  for (const item of schedules) {
    if (!item.end_date) continue;
    const days = daysUntil(item.end_date);
    const info = scheduleDesc(item);

    // 生成条件：未开始且距开始<=配置天数 | 已开始且距截止<=配置天数 | 已过期未完成
    const shouldGenerate =
      (item.start_date && item.start_date > today && info.daysLeftNum <= scheduleDays) ||
      (days >= 0 && days <= scheduleDays) ||
      (days < 0);

    if (shouldGenerate) {
      const existing = await queryFirst(
        "SELECT id FROM reminders WHERE module_type = ? AND module_id = ? AND is_active = 1 AND dismissed = 0",
        ["schedule", item.id]
      );
      if (!existing) {
        await insert(TABLE, {
          module_type: "schedule",
          module_id: item.id,
          title: item.title,
          description: info.desc,
          remind_time: item.end_date,
          priority: item.priority || "medium",
          is_active: 1,
          dismissed: 0,
        });
      }
    }
  }
}

async function autoGenerateDurableExpiryReminders(durableDays) {
  const durables = await query(
    "SELECT * FROM durables WHERE expiry_date != '' AND status = 'in_use'"
  );
  // 建立有效物品 → 过期日期映射
  const validMap = new Map();
  for (const item of durables) {
    validMap.set(item.id, item.expiry_date);
  }

  // 清理脏数据：停用 remind_time 与当前 expiry_date 不匹配的旧提醒 + 去重
  const activeDurableReminders = await query(
    "SELECT * FROM reminders WHERE module_type = 'durable' AND is_active = 1 AND dismissed = 0"
  );
  const durableReminderMap = new Map();
  for (const r of activeDurableReminders) {
    const currentExpiry = validMap.get(r.module_id);
    if (!currentExpiry || r.remind_time !== currentExpiry) {
      await update(TABLE, r.id, { is_active: 0 });
      continue;
    }
    // 同一 module_id 有多条记录时，保留最新的，停用其余的
    const existing = durableReminderMap.get(r.module_id);
    if (existing) {
      await update(TABLE, r.id, { is_active: 0 });
    } else {
      durableReminderMap.set(r.module_id, r);
    }
  }

  for (const item of durables) {
    if (!item.expiry_date) continue;
    const days = daysUntil(item.expiry_date);

    // 生成条件：未过期且距过期<=配置天数 | 已过期
    const shouldGenerate = (days >= 0 && days <= durableDays) || (days < 0);

    if (shouldGenerate) {
      const existing = await queryFirst(
        "SELECT id FROM reminders WHERE module_type = ? AND module_id = ? AND is_active = 1 AND dismissed = 0",
        ["durable", item.id]
      );
      if (!existing) {
        const info = durableDesc(item);
        await insert(TABLE, {
          module_type: "durable",
          module_id: item.id,
          title: item.name,
          description: info.desc,
          remind_time: item.expiry_date,
          priority: days <= 0 ? "high" : "medium",
          is_active: 1,
          dismissed: 0,
        });
      }
    }
  }
}

async function autoGenerateImportantDateReminders(importantDateDays) {
  const importantDates = await query(
    "SELECT * FROM important_dates WHERE reminder_enabled = 1"
  );

  // 建立有效 ID 集合
  const validSet = new Set(importantDates.map((d) => d.id));

  // 清理不再符合条件的旧提醒 + 去重
  const activeReminders = await query(
    "SELECT * FROM reminders WHERE module_type = 'important_date' AND is_active = 1 AND dismissed = 0"
  );
  const reminderMap = new Map();
  for (const r of activeReminders) {
    if (!validSet.has(r.module_id)) {
      await update(TABLE, r.id, { is_active: 0 });
      continue;
    }
    const existing = reminderMap.get(r.module_id);
    if (existing) {
      await update(TABLE, r.id, { is_active: 0 });
    } else {
      reminderMap.set(r.module_id, r);
    }
  }

  for (const item of importantDates) {
    const next = computeNextOccurrence(item.date, item.type);
    if (!next || next.daysUntil < 0) continue;

    const daysBefore = item.reminder_days_before || 1;
    if (next.daysUntil > daysBefore) continue;

    const correctRemindTime = formatLocalDate(next.date);
    const existing = await queryFirst(
      "SELECT id, remind_time FROM reminders WHERE module_type = ? AND module_id = ? AND is_active = 1 AND dismissed = 0",
      ["important_date", item.id]
    );
    if (!existing) {
      await insert(TABLE, {
        module_type: "important_date",
        module_id: item.id,
        title: item.name,
        description: "common.daysLeft",
        remind_time: correctRemindTime,
        priority: "medium",
        is_active: 1,
        dismissed: 0,
      });
    } else if (existing.remind_time !== correctRemindTime) {
      await update(TABLE, existing.id, { remind_time: correctRemindTime });
    }
  }
}

export const fetchReminderList = async (params = {}) => {
  try {
    const config = await getRemindConfig();
    await ensureRemindersGenerated();
    const rows = await getAll(TABLE, "created_at DESC");

    // 批量查询源数据（仅未开始/未完成状态的计划）
    const schedules = await query("SELECT * FROM schedules WHERE reminder_enabled = 1 AND status != 'done' AND status != 'in_progress'");
    const scheduleMap = new Map(schedules.map((s) => [s.id, s]));
    const durables = await query("SELECT * FROM durables WHERE expiry_date != '' AND status = 'in_use'");
    const durableMap = new Map(durables.map((d) => [d.id, d]));

    const data = rows
      .filter((r) => r.is_active === 1 && r.dismissed === 0)
      .map((r) => {
        let info;
        if (r.module_type === "schedule") {
          const s = scheduleMap.get(r.module_id);
          info = s ? scheduleDesc(s) : { desc: r.description || "", daysLeft: "", daysLeftNum: 999 };
        } else if (r.module_type === "durable") {
          const d = durableMap.get(r.module_id);
          info = d ? durableDesc(d) : { desc: r.description || "", daysLeft: "", daysLeftNum: 999 };
        } else if (r.module_type === "important_date") {
          const days = r.remind_time ? daysUntil(r.remind_time) : 999;
          info = { desc: "common.daysLeft", descCount: days >= 0 ? days : 0, daysLeft: days >= 0 ? String(days) : "0", daysLeftNum: days };
        } else {
          const days = r.remind_time ? daysUntil(r.remind_time) : 999;
          info = { desc: r.description || "", daysLeft: days < 0 ? "common.expired" : String(days), daysLeftNum: days };
        }
        return {
          id: r.id,
          title: r.title,
          desc: info.desc,
          descCount: info.descCount,
          daysLeft: info.daysLeft,
          daysLeftNum: info.daysLeftNum,
          moduleType: r.module_type,
          moduleId: r.module_id,
          priority: r.priority,
          isActive: true,
        };
      })
      .filter((r) => {
        if (r.moduleType === "schedule") {
          const s = scheduleMap.get(r.moduleId);
          if (!s) return false;
          const today = todayLocal();
          const endDays = s.end_date ? daysUntil(s.end_date) : 999;
          if (s.start_date && s.start_date > today) return daysUntil(s.start_date) <= config.scheduleDays;
          return endDays <= config.scheduleDays;
        }
        if (r.moduleType === "durable") return r.daysLeftNum <= config.durableDays;
        // important_date 由自身 reminder_days_before 控制，不再用全局配置过滤
        if (r.moduleType === "important_date") return true;
        return true;
      });

    // 按 module_type + module_id 去重，保留最新的一条
    const seen = new Set();
    const deduped = [];
    for (const item of data) {
      const key = `${item.moduleType}_${item.moduleId}`;
      if (!seen.has(key)) {
        seen.add(key);
        deduped.push(item);
      }
    }
    return wrapSuccess(deduped);
  } catch (e) {
    return wrapFail(e.message);
  }
};

/**
 * 获取消息提醒页面数据：
 * - 开启提醒且状态为未开始/未完成的计划
 * - 即将过期/已过期的物品（expiry_date 不为空）
 * 计划排前面（按优先级+最近计划排序），物品排后面（按距过期天数升序）
 */
export const fetchMessageList = async () => {
  try {
    const config = await getRemindConfig();
    await ensureRemindersGenerated();

    // 开启提醒且状态为未开始/未完成的计划
    const schedules = await query(
      "SELECT * FROM schedules WHERE reminder_enabled = 1 AND status != 'done' AND status != 'in_progress'"
    );
    const today = todayLocal();
    const scheduleItems = schedules
      .map((s) => {
        const info = scheduleDesc(s);
        return {
          id: `schedule_${s.id}`,
          moduleId: s.id,
          moduleType: "schedule",
          title: s.title,
          desc: info.desc,
          descCount: info.descCount,
          priority: s.priority || "medium",
          daysLeft: info.daysLeft,
          daysLeftNum: info.daysLeftNum,
          remindTime: s.end_date || "",
        };
      })
      .filter((item) => {
        const s = schedules.find((s) => s.id === item.moduleId);
        if (!s) return false;
        const endDays = s.end_date ? daysUntil(s.end_date) : 999;
        if (s.start_date && s.start_date > today) return daysUntil(s.start_date) <= config.scheduleDays;
        return endDays <= config.scheduleDays;
      });

    // 排序：优先级升序 → 最近计划（end_date 升序）
    scheduleItems.sort((a, b) => {
      const pa = PRIORITY_ORDER[a.priority] ?? 1;
      const pb = PRIORITY_ORDER[b.priority] ?? 1;
      if (pa !== pb) return pa - pb;
      return (a.remindTime || "").localeCompare(b.remindTime || "");
    });

    // 即将过期（<=配置天数）或已过期的使用中物品
    const durables = await query(
      "SELECT * FROM durables WHERE expiry_date != '' AND status = 'in_use'"
    );
    const durableItems = durables
      .map((d) => {
        const info = durableDesc(d);
        return {
          id: `durable_${d.id}`,
          moduleId: d.id,
          moduleType: "durable",
          title: d.name,
          desc: info.desc,
          descCount: info.descCount,
          priority: info.daysLeftNum <= 0 ? "high" : info.daysLeftNum <= 1 ? "high" : "medium",
          daysLeft: info.daysLeft,
          daysLeftNum: info.daysLeftNum,
          remindTime: d.expiry_date || "",
        };
      })
      .filter((d) => d.daysLeftNum <= config.durableDays);

    // 物品按距过期天数升序（已过期的排最前）
    durableItems.sort((a, b) => a.daysLeftNum - b.daysLeftNum);

    // 开启提醒的重要日子
    const importantDates = await query(
      "SELECT * FROM important_dates WHERE reminder_enabled = 1"
    );
    const importantDateItems = [];
    for (const d of importantDates) {
      const next = computeNextOccurrence(d.date, d.type);
      if (!next || next.daysUntil < 0) continue;
      const daysBefore = d.reminder_days_before || 1;
      if (next.daysUntil > daysBefore) continue;
      importantDateItems.push({
        id: `important_date_${d.id}`,
        moduleId: d.id,
        moduleType: "important_date",
        title: d.name,
        desc: "common.daysLeft",
        descCount: next.daysUntil,
        priority: "medium",
        daysLeft: String(next.daysUntil),
        daysLeftNum: next.daysUntil,
        remindTime: formatLocalDate(next.date),
      });
    }
    importantDateItems.sort((a, b) => a.daysLeftNum - b.daysLeftNum);

    const data = [...scheduleItems, ...durableItems, ...importantDateItems];
    return wrapSuccess(data);
  } catch (e) {
    return wrapFail(e.message);
  }
};
